### ISSUE TITLE
"Unsupported vm::cast() type"

### ISSUE THREAD

**Issue by devilmac** [DHrpcs3/rpcs3#994] opened 2015-02-08 09:46 UTC
Hi all,

I'm trying to build this project but I get this error:

In file included from /Users/federico/Downloads/rpcs3/rpcs3/Emu/ARMv7/ARMv7Thread.cpp:4:
In file included from /Users/federico/Downloads/rpcs3/rpcs3/Emu/Memory/Memory.h:144:
/Users/federico/Downloads/rpcs3/rpcs3/Emu/Memory/vm.h:79:3: error: static_assert failed "Unsupported vm::cast() type"
                static_assert(std::is_same<T, u32>::value, "Unsupported vm::cast() type");
                ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/federico/Downloads/rpcs3/rpcs3/Emu/Memory/vm.h:123:10: note: in instantiation of template class 'vm::cast_ptr<unsigned long>' requested here
                return cast_ptr<T>::cast(addr, func);
                       ^
/Users/federico/Downloads/rpcs3/rpcs3/Emu/ARMv7/ARMv7Thread.cpp:259:28: note: in instantiation of function template specialization
      'vm::cast<unsigned long>' requested here
                const u32 arg_size = vm::cast(arg.size(), "arg.size()"); // get arg size
                                         ^
1 error generated.
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/Emu/ARMv7/ARMv7Thread.cpp.o] Error 1
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
make: *** [all] Error 2

Could you help me to resolve it?

Many thanks guys :D

**Comment by Syphurith** [comment] 2015-02-09 06:53
is_same is a C++ template, see [Here](http://www.cplusplus.com/reference/type_traits/is_same/). There it should be used to check whether the pointer can be cast to the other. So simply saying, the two types in the line pointed out from vm.h caused you some troubles.
Would you please tell us your system and MSVC/GCC/Clang version?
I think it may be caused by two reason:
* rpcs3 is supposed to be built successfully on 64 bit system (x86_64 preferred, don't know those ia64) only, currently. PS3's CPU is 64 bit CELL. If you're trying to build on a 32 bit system (i486/i586/i686 and so), the function pointer should be 32 bits, when the address on PS3 stays 64 bits. (BTW most of Apple Mactonishes are 64 bits)
* If your compiler doesn't support C++ 11 well enough, thus asserts should fail. (Think about trying to build this with GCC 3.4.4 ..) Eh.. i thought you were using GCC with CMake and make.

The maintainer only merge the pull requests passed the intergration test (for example, Travis-CI). So this issue seems to be quite special if you are trying the master branch of DHrpcs3.

Hope this may help you solve the problem.

**Comment by robxu9** [comment] 2015-02-10 04:11
I tried building this on a Mac and I hit a couple of these points:

Mac seems to automatically substitute u32 for unsigned int and u64 for unsigned long in the casts, and the compiler doesn't like how u64 != unsigned long, so it errors out.

**Comment by devilmac** [comment] 2015-02-10 11:07
Hi @Syphurith 

at the moment I don't remember which compiler is used on my Mac.
This evening I can tell you more in detail.

**Comment by Syphurith** [comment] 2015-02-10 14:23
@devilmac First there is an faster way for you to get which the compiler is. Just execute `which cc`(well you should have `which`), it would tell you where that `cc` (default name for C compiler) is. And use `ls -ll` to get its linked target, or just `cc -v` or `cc --version` to get some info.

If unfortunately (that is a default name for c compiler), try to trace it through CMake's Cache:

1. Try finding the file `CMakeCache.txt`. The file should be in your build folder, which is for example `/Users/federico/Downloads/rpcs3/build`.

2. Search the file for `CMAKE_CXX_COMPILER` and `CMAKE_C_COMPILER`, these would tell you which compiler is used. For example, `CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/c++` tells you that `/usr/bin/c++` is used for C++ compiler. Well you may ever want to see which file it links to, try `ls -ll /usr/bin/c++` then, it may tells you it links to `gcc`.

3. Try execute something as `cc --version` (and `cc -v`). This would tell you the full release name of the compiler executable and some more info. Okey good i got `Target: x86_64-pc-cygwin` for that test program. Yes i did try to compile something with cygwin64.

If you've already have XCode Installed, a usable Clang may already be on your mac.

**Comment by Syphurith** [comment] 2015-02-10 14:43
@robxu9 Ha. Someone on [Stackoverflow](http://stackoverflow.com/questions/1455720/mac-osx-10-6-compiler-a-puzzling-experience-with-32-vs-64-bit) told a story that `arch` command gave him `i686`(32 bits).

**Comment by robxu9** [comment] 2015-02-10 15:10
@Syphurith I wouldn't be surprised... I have to manually push `-arch x86_64` just to build rpcs3 (because apparently I build `-arch ` (without any arch definition))

**Comment by Syphurith** [comment] 2015-02-10 15:29
@robxu9 You succeeded, or not? *If that is indeed a required mark for building rpcs3 with CMake and Apple Mac* , somewhere inside CMakeLists.txt should be changed.

**Comment by devilmac** [comment] 2015-02-10 19:51
@Syphurith the C compiler of my Mac is

Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix

I retry to build the project and I see if it succeed or not.

**Comment by Syphurith** [comment] 2015-02-11 05:06
@devilmac So your machine should be 64 bits already. If you want to modify the CMake: There're 3 CMakeLists.txt in the repo (one for rpcs3, one for asmjit and one for the repo. well.. omit the llvm and wxWidgets). Cause the rpcs3 is your final linked executable, i think you can open the CMakeLists.txt under /rpcs3/rpcs3, and edit around its 40th line:
```
if (APPLE)
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -I/opt/X11/include")
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -I/opt/X11/include")
endif()
```
to
```
if (APPLE)
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -arch x86_64 -I/opt/X11/include")
	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -arch x86_64 -I/opt/X11/include")
endif()
```
to see if that make any difference. `CMAKE_C_FLAGS` for C compiler, and `CMAKE_CXX_FLAGS` for C++ compiler. If not so lucky try download or even compile a x86_64 GCC compiler, and re-run CMake to modify the toolchain. 
@robxu9 may have already built rpcs3 successfully, you may ask him for some help. 
Well i'm on Win8, and I'm just a noob with CMake.. I suggust you to google for some answer about CMake. You're using LLVM with Clang, and this may even need you to add more marks for the build.

**Comment by robxu9** [comment] 2015-02-16 01:36
Yeah - I got rpcs3 working on Yosemite, and that should have been pulled into master. Do a clean checkout, make sure you have an LLVM with JIT, and build away.

**Comment by Syphurith** [comment] 2015-02-16 06:00
@robxu9 well that's good. If solved fully don't forget to close this. Bye

**Comment by devilmac** [comment] 2015-02-17 20:46
Hi all,
I was too close to finish the build! but I've got this error:

[ 83%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/Utilities/StrFmt.cpp.o
[ 83%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/Utilities/Thread.cpp.o
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:255:1: warning: control may reach end of non-void function [-Wreturn-type]
}
^
1 warning generated.
Linking CXX executable ../bin/rpcs3
ld: library not found for -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/rpcs3] Error 1
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
make: *** [all] Error 2

What this means?

Thanks a lot!

**Comment by Syphurith** [comment] 2015-02-18 07:43
This issue was already fixed by @Bigpet. According to #997 simply you can add `rt` to `rpcs3/CMakeLists.txt` line 123. or say, change
```
target_link_libraries(rpcs3  asmjit.a  ${wxWidgets_LIBRARIES} ${OPENAL_LIBRARY} ${GLEW_LIBRARY} ${OPENGL_LIBRARIES} libavformat.a libavcodec.a libavutil.a libswresample.a libswscale.a ${ZLIB_LIBRARIES} ${LLVM_LIBS})
```
to
```
target_link_libraries(rpcs3  asmjit.a  ${wxWidgets_LIBRARIES} ${OPENAL_LIBRARY} ${GLEW_LIBRARY} ${OPENGL_LIBRARIES} libavformat.a libavcodec.a libavutil.a libswresample.a libswscale.a ${ZLIB_LIBRARIES} ${LLVM_LIBS} rt)
```
And it would finish the linking.
I saw @robxu9 already made a pull for the fix, however I'm not totally satisfied with it. I suggust you to test if `-arch x86_64` would work. I thought there may be more `u64` or the types related to the issue, and i don't think test APPLE there would be good enough. @robxu9, sorry for that.

**Comment by Bigpet** [comment] 2015-02-18 07:48
@Syphurith  maybe the issue is that on macos `-lrt` is not needed (it's not needed on Ubuntu either) and fails the build.

**Comment by Syphurith** [comment] 2015-02-18 14:20
@Bigpet Sorry i thought it should need to add `-lrt` incorrectly. There is `rt` embed in GCC libstdcxx, but for Clang that is [a seperate library](http://compiler-rt.llvm.org/) as `compiler-rt`. Since @devilmac use Clang with LLVM, he may need to build this library (even build the clang with it) before linking.
Well Hope this can be built successfully then.

**Comment by Bigpet** [comment] 2015-02-18 14:29
compiler-rt has nothing to do with librt the realtime library.

Also, the functions which we added it for ("shm_unlink" and friends) seem to be available in OSX without librt. So what we need is to just add "rt" on Linux and not on other platforms

**Comment by Syphurith** [comment] 2015-02-18 15:06
@Bigpet oh wait a while, dear. @robxu9 is using a Mac now but he may use GCC instead of Clang. 
For this, you can see the pull request #1008. Eh.. maybe we should test Clang instead of just Apple?

**Comment by Bigpet** [comment] 2015-02-18 15:13
I assume it was building fine for him before #999 as well. I can't find any reference of gcc shipping with librt under OSX.

**Comment by Syphurith** [comment] 2015-02-18 15:14
Okey, we may contact him some time after.

**Comment by devilmac** [comment] 2015-02-18 16:53
@Syphurith Ok, when I'll be at home I'll try!
Thanks a lot for the help.

**Comment by boxingcow** [comment] 2015-02-18 17:58
Building this on my Mac works fine until it reaches librt, after fixing the offending lines compilation then fails with 
>Linking CXX executable ../bin/rpcs3
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      L10nConvertStr(int, vm::ps3::ptr<void const, 1, unsigned int>, vm::ps3::ptr<unsigned int, 1, unsigned int>, int, vm::ps3::ptr<void, 1, unsigned int>, vm::ps3::ptr<unsigned int, 1, unsigned int>) in cellL10n.cpp.o
      _avcodec_decode_subtitle2 in libavcodec.a(utils.o)
  "_iconv_close", referenced from:
      L10nConvertStr(int, vm::ps3::ptr<void const, 1, unsigned int>, vm::ps3::ptr<unsigned int, 1, unsigned int>, int, vm::ps3::ptr<void, 1, unsigned int>, vm::ps3::ptr<unsigned int, 1, unsigned int>) in cellL10n.cpp.o
      _avcodec_open2 in libavcodec.a(utils.o)
      _avcodec_decode_subtitle2 in libavcodec.a(utils.o)
  "_iconv_open", referenced from:
      L10nConvertStr(int, vm::ps3::ptr<void const, 1, unsigned int>, vm::ps3::ptr<unsigned int, 1, unsigned int>, int, vm::ps3::ptr<void, 1, unsigned int>, vm::ps3::ptr<unsigned int, 1, unsigned int>) in cellL10n.cpp.o
      _avcodec_open2 in libavcodec.a(utils.o)
      _avcodec_decode_subtitle2 in libavcodec.a(utils.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/rpcs3] Error 1
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
make: *** [all] Error 2

**Comment by Syphurith** [comment] 2015-02-18 18:05
@boxingcow well have you installed `iconv` library? `L10nConvertStr` may cause you some troubles, since i used Windows SDK functions for Windows platform, and the design in doc is certainly iconv equivlant - so i picked iconv to be the one used with GCC. If you would like you can try get the iconv library and link it (or, add it to the CMakeLists.txt where `rt` had been). Or centainly you can comment the function and disable it. Indeed i'm wondering how can it be done without iconv, on Mac.

**Comment by boxingcow** [comment] 2015-02-18 18:08
Ah, it just needed adding to the CMake file. Now it compiles just fine, not sure about function though, that will have to wait till later.

**Comment by devilmac** [comment] 2015-02-20 18:14
Hi all,

it seems that I won't never build this library XD.
I got the error below:

[100%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/__/Utilities/Thread.cpp.o
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:512:1: warning: control may reach end of non-void function [-Wreturn-type]
}
^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:606:52: warning: '&' within '|' [-Wbitwise-op-parentheses]
                case 1: *X64REG(context, reg - X64R_RAX) = value & 0xff | *X64REG(context, reg - X64R_RAX) & 0xffffff00; return true;
                                                           ~~~~~~^~~~~~ ~
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:606:52: note: place parentheses around the '&' expression to silence this warning
                case 1: *X64REG(context, reg - X64R_RAX) = value & 0xff | *X64REG(context, reg - X64R_RAX) & 0xffffff00; return true;
                                                                 ^
                                                           (           )
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:606:94: warning: '&' within '|' [-Wbitwise-op-parentheses]
                case 1: *X64REG(context, reg - X64R_RAX) = value & 0xff | *X64REG(context, reg - X64R_RAX) & 0xffffff00; return true;
                                                                        ~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:606:94: note: place parentheses around the '&' expression to silence this warning
                case 1: *X64REG(context, reg - X64R_RAX) = value & 0xff | *X64REG(context, reg - X64R_RAX) & 0xffffff00; return true;
                                                                                                           ^
                                                                          (                                            )
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:607:52: warning: '&' within '|' [-Wbitwise-op-parentheses]
                case 2: *X64REG(context, reg - X64R_RAX) = value & 0xffff | *X64REG(context, reg - X64R_RAX) & 0xffff0000; return true;
                                                           ~~~~~~^~~~~~~~ ~
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:607:52: note: place parentheses around the '&' expression to silence this warning
                case 2: *X64REG(context, reg - X64R_RAX) = value & 0xffff | *X64REG(context, reg - X64R_RAX) & 0xffff0000; return true;
                                                                 ^
                                                           (             )
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:607:96: warning: '&' within '|' [-Wbitwise-op-parentheses]
                case 2: *X64REG(context, reg - X64R_RAX) = value & 0xffff | *X64REG(context, reg - X64R_RAX) & 0xffff0000; return true;
                                                                          ~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:607:96: note: place parentheses around the '&' expression to silence this warning
                case 2: *X64REG(context, reg - X64R_RAX) = value & 0xffff | *X64REG(context, reg - X64R_RAX) & 0xffff0000; return true;
                                                                                                             ^
                                                                            (                                            )
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:634:3: error: no member named '__eflags' in '__darwin_x86_thread_state64'; did you mean
      '__rflags'?
                EFLAGS(context) |= 0x1; // set CF
                ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:468:55: note: expanded from macro 'EFLAGS'
#define EFLAGS(context) ((context)->uc_mcontext->__ss.__eflags)
                                                      ^
/usr/include/mach/i386/_structs.h:473:13: note: '__rflags' declared here
        __uint64_t      __rflags;
                        ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:638:3: error: no member named '__eflags' in '__darwin_x86_thread_state64'; did you mean
      '__rflags'?
                EFLAGS(context) &= ~0x1; // clear CF
                ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:468:55: note: expanded from macro 'EFLAGS'
#define EFLAGS(context) ((context)->uc_mcontext->__ss.__eflags)
                                                      ^
/usr/include/mach/i386/_structs.h:473:13: note: '__rflags' declared here
        __uint64_t      __rflags;
                        ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:643:3: error: no member named '__eflags' in '__darwin_x86_thread_state64'; did you mean
      '__rflags'?
                EFLAGS(context) |= 0x40; // set ZF
                ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:468:55: note: expanded from macro 'EFLAGS'
#define EFLAGS(context) ((context)->uc_mcontext->__ss.__eflags)
                                                      ^
/usr/include/mach/i386/_structs.h:473:13: note: '__rflags' declared here
        __uint64_t      __rflags;
                        ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:647:3: error: no member named '__eflags' in '__darwin_x86_thread_state64'; did you mean
      '__rflags'?
                EFLAGS(context) &= ~0x40; // clear ZF
                ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:468:55: note: expanded from macro 'EFLAGS'
#define EFLAGS(context) ((context)->uc_mcontext->__ss.__eflags)
                                                      ^
/usr/include/mach/i386/_structs.h:473:13: note: '__rflags' declared here
        __uint64_t      __rflags;
                        ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:652:3: error: no member named '__eflags' in '__darwin_x86_thread_state64'; did you mean
      '__rflags'?
                EFLAGS(context) |= 0x80; // set SF
                ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:468:55: note: expanded from macro 'EFLAGS'
#define EFLAGS(context) ((context)->uc_mcontext->__ss.__eflags)
                                                      ^
/usr/include/mach/i386/_structs.h:473:13: note: '__rflags' declared here
        __uint64_t      __rflags;
                        ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:656:3: error: no member named '__eflags' in '__darwin_x86_thread_state64'; did you mean
      '__rflags'?
                EFLAGS(context) &= ~0x80; // clear SF
                ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:468:55: note: expanded from macro 'EFLAGS'
#define EFLAGS(context) ((context)->uc_mcontext->__ss.__eflags)
                                                      ^
/usr/include/mach/i386/_structs.h:473:13: note: '__rflags' declared here
        __uint64_t      __rflags;
                        ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:661:3: error: no member named '__eflags' in '__darwin_x86_thread_state64'; did you mean
      '__rflags'?
                EFLAGS(context) |= 0x800; // set OF
                ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:468:55: note: expanded from macro 'EFLAGS'
#define EFLAGS(context) ((context)->uc_mcontext->__ss.__eflags)
                                                      ^
/usr/include/mach/i386/_structs.h:473:13: note: '__rflags' declared here
        __uint64_t      __rflags;
                        ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:665:3: error: no member named '__eflags' in '__darwin_x86_thread_state64'; did you mean
      '__rflags'?
                EFLAGS(context) &= ~0x800; // clear OF
                ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:468:55: note: expanded from macro 'EFLAGS'
#define EFLAGS(context) ((context)->uc_mcontext->__ss.__eflags)
                                                      ^
/usr/include/mach/i386/_structs.h:473:13: note: '__rflags' declared here
        __uint64_t      __rflags;
                        ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:674:3: error: no member named '__eflags' in '__darwin_x86_thread_state64'; did you mean
      '__rflags'?
                EFLAGS(context) |= 0x4; // set PF
                ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:468:55: note: expanded from macro 'EFLAGS'
#define EFLAGS(context) ((context)->uc_mcontext->__ss.__eflags)
                                                      ^
/usr/include/mach/i386/_structs.h:473:13: note: '__rflags' declared here
        __uint64_t      __rflags;
                        ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:678:3: error: no member named '__eflags' in '__darwin_x86_thread_state64'; did you mean
      '__rflags'?
                EFLAGS(context) &= ~0x4; // clear PF
                ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:468:55: note: expanded from macro 'EFLAGS'
#define EFLAGS(context) ((context)->uc_mcontext->__ss.__eflags)
                                                      ^
/usr/include/mach/i386/_structs.h:473:13: note: '__rflags' declared here
        __uint64_t      __rflags;
                        ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:683:3: error: no member named '__eflags' in '__darwin_x86_thread_state64'; did you mean
      '__rflags'?
                EFLAGS(context) |= 0x10; // set AF
                ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:468:55: note: expanded from macro 'EFLAGS'
#define EFLAGS(context) ((context)->uc_mcontext->__ss.__eflags)
                                                      ^
/usr/include/mach/i386/_structs.h:473:13: note: '__rflags' declared here
        __uint64_t      __rflags;
                        ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:687:3: error: no member named '__eflags' in '__darwin_x86_thread_state64'; did you mean
      '__rflags'?
                EFLAGS(context) &= ~0x10; // clear AF
                ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:468:55: note: expanded from macro 'EFLAGS'
#define EFLAGS(context) ((context)->uc_mcontext->__ss.__eflags)
                                                      ^
/usr/include/mach/i386/_structs.h:473:13: note: '__rflags' declared here
        __uint64_t      __rflags;
                        ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:697:7: error: no member named '__eflags' in '__darwin_x86_thread_state64'; did you mean
      '__rflags'?
                if (EFLAGS(context) & 0x400 /* direction flag */)
                    ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:468:55: note: expanded from macro 'EFLAGS'
#define EFLAGS(context) ((context)->uc_mcontext->__ss.__eflags)
                                                      ^
/usr/include/mach/i386/_structs.h:473:13: note: '__rflags' declared here
        __uint64_t      __rflags;
                        ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:829:36: error: type 'struct __darwin_xmm_reg' does not provide a subscript operator
                                memcpy(vm::get_priv_ptr(addr), XMMREG(context, reg - X64R_XMM0), 16);
                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:467:95: note: expanded from macro 'XMMREG'
#define XMMREG(context, reg) (reinterpret_cast<u128*>(&(context)->uc_mcontext->__fs.__fpu_xmm0[reg]))
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:867:9: error: no member named '__eflags' in '__darwin_x86_thread_state64'; did you mean
      '__rflags'?
                                if (EFLAGS(context) & 0x400 /* direction flag */)
                                    ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:468:55: note: expanded from macro 'EFLAGS'
#define EFLAGS(context) ((context)->uc_mcontext->__ss.__eflags)
                                                      ^
/usr/include/mach/i386/_structs.h:473:13: note: '__rflags' declared here
        __uint64_t      __rflags;
                        ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:925:9: error: no member named '__eflags' in '__darwin_x86_thread_state64'; did you mean
      '__rflags'?
                                if (EFLAGS(context) & 0x400 /* direction flag */)
                                    ^
/Users/federico/Downloads/rpcs3/Utilities/Thread.cpp:468:55: note: expanded from macro 'EFLAGS'
#define EFLAGS(context) ((context)->uc_mcontext->__ss.__eflags)
                                                      ^
/usr/include/mach/i386/_structs.h:473:13: note: '__rflags' declared here
        __uint64_t      __rflags;
                        ^
5 warnings and 16 errors generated.
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/__/Utilities/Thread.cpp.o] Error 1
make[1]: *** [rpcs3/CMakeFiles/rpcs3.dir/all] Error 2
make: *** [all] Error 2

Sorry.

**Comment by Bigpet** [comment] 2015-02-20 18:18
@devilmac please don't post huge logs directly, paste them somewhere else and link that (for example gist.github.com )

Also, those errors are still from you trying to compile for 32-bit which we do not support

**Comment by Syphurith** [comment] 2015-02-21 04:36
@devilmac `__eflags` and `__ss` seems to be related to SSE instruction sets. Your machine should support SSE or else your cpu is quite obselete. Please check your CPU product name, like `intel core i5-3220M`, you can see this from any hardware detection software or your "about mactonish", or you can check it out when search for your mac (like `iMac XXXX`) and its specification may tell you about it.
If really you cpu support SSE, you can check if using command line to manually compile the single file would work. You may need to google for something like "enable SSE instruction Clang Mac".
BTW, you should use [gist](http://gist.github.com) or pastebin or something else (i recommend you use gist) to hold your hugh log. And you can go to our irc and ask for some help when necessary.

**Comment by robxu9** [comment] 2015-02-21 06:45
@Syphurith I'm using clang. Can't use gcc to built asmjit.

**Comment by Syphurith** [comment] 2015-02-21 13:05
@robxu9 well that's a little unexpected. So asmjit may even produce some errors for you with gcc.

**Comment by robxu9** [comment] 2015-02-21 13:34
That's because GCC doesn't support some of the asm codes - so clang is
practically required...

Use clang anyway. GCC isn't supported on OSX anymore.

**Comment by Syphurith** [comment] 2015-02-22 08:45
@robxu9 (using email to reply, cool) Ok i understand it, thanks.
MSVC for windows, GCC for linux and Clang for OSX .. ha.

**Comment by Nekotekina** [comment] 2015-02-28 19:39
Seems __eflags should be __rflags. I'll commit it.

**Comment by robxu9** [comment] 2015-02-28 23:09
I'm assuming that was added in a later commit.

We should probably add OS X support to Travis CI? They have OS X builders; you have to email support to enable it (and it's been really quick for me) and then enable it in .travis.yml.

**Comment by sturmE** [comment] 2015-03-01 07:45
In order to make it build on osx I had to change:

```
--- a/Utilities/Thread.cpp
+++ b/Utilities/Thread.cpp
@@ -464,8 +464,8 @@ typedef ucontext_t x64_context;
 #ifdef __APPLE__

 #define X64REG(context, reg) (darwin_x64reg(context, reg))
-#define XMMREG(context, reg) (reinterpret_cast<u128*>(&(context)->uc_mcontext->__fs.__fpu_xmm0[reg]))
-#define EFLAGS(context) ((context)->uc_mcontext->__ss.__eflags)
+#define XMMREG(context, reg) (reinterpret_cast<u128*>(&(context)->uc_mcontext->__fs.__fpu_xmm0.__xmm_reg[reg]))
+#define EFLAGS(context) ((context)->uc_mcontext->__ss.__rflags)
```

With these changes I was able to compile and run but it crashes when trying to boot an elf or game. The output of the error is:

```
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: recursive_mutex lock failed: Invalid argument
```

Looking at the backtrace in lldb, the problem occurs in the destructor of MemoryBase on the call to ```LV2_LOCK(0);``` in ```MemoryBase::Close()```. That's as far as I got.

**Comment by robxu9** [comment] 2015-03-01 18:02
Well, LV2_LOCK is defined here:
https://github.com/DHrpcs3/rpcs3/blob/31bf130b1c7acf78ef334a2bdb0550971e6d2821/rpcs3/Emu/System.h#L202.
..

On 1 March 2015 at 02:45, Eugene Sturm <notifications@github.com> wrote:

> In order to make it build on osx I had to change:
>
> --- a/Utilities/Thread.cpp
> +++ b/Utilities/Thread.cpp
> @@ -464,8 +464,8 @@ typedef ucontext_t x64_context;
>  #ifdef __APPLE__
>
>  #define X64REG(context, reg) (darwin_x64reg(context, reg))
> -#define XMMREG(context, reg) (reinterpret_cast<u128*>(&(context)->uc_mcontext->__fs.__fpu_xmm0[reg]))
> -#define EFLAGS(context) ((context)->uc_mcontext->__ss.__eflags)
> +#define XMMREG(context, reg) (reinterpret_cast<u128*>(&(context)->uc_mcontext->__fs.__fpu_xmm0.__xmm_reg[reg]))
> +#define EFLAGS(context) ((context)->uc_mcontext->__ss.__rflags)
>
> With these changes I was able to compile and run but it crashes when
> trying to boot an elf or game. The output of the error is:
>
> libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: recursive_mutex lock failed: Invalid argument
>
> Looking at the backtrace in lldb, the problem occurs in the destructor of
> MemoryBase on the call to LV2_LOCK(0); in MemoryBase::Close(). That's as
> far as I got.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DHrpcs3/rpcs3/issues/994#issuecomment-76586750>.
>



-- 
cheers, Robert :: github.com/robxu9

**Comment by sturmE** [comment] 2015-03-01 21:03
Ya I saw that. Runtime error occurs in construction of lock_guard. Looking at docs, http://en.cppreference.com/w/cpp/thread/lock_guard/lock_guard, I see some specific logic targeted towards recursive_mutex 

```
1) If m is not a recursive mutex, requires that the current thread does not own m. Effectively calls m.lock().
2) Requires that the current thread owns m.
```

Unfortunately, my knowledge is very shallow in this area.

**Comment by Nekotekina** [comment] 2015-03-01 21:29
Isn't it related with some bug in OSX with recursive mutexes? Just accidentally googled about it: http://lists.gnu.org/archive/html/bug-gnulib/2013-05/msg00040.html

**Comment by sturmE** [comment] 2015-03-01 21:44
That looks like just for 10.6. I am testing this out on 10.10. I couldn't find anything saying this issue exists on > 10.6. The only thing I found was this: 

http://knowledge.autodesk.com/search-result/caas/CloudHelp/cloudhelp/2015/ENU/Maya-SDK/files/GUID-EE052898-C59C-438A-9A77-798F5BEB7A77-htm.html

Which does say "There is no static initializer for pthread_rwlock_t or recursive mutex." But we aren't statically initializing recursive mutex.

**Comment by sturmE** [comment] 2015-03-01 21:51
I also verified by just writing a quick program that does the same behavior:

```
int main(int argc, char** argv) {
    std::recursive_mutex recursive_mutex;
    std::lock_guard<std::recursive_mutex> lock(recursive_mutex);
    return 0;
}
```

This executes just fine. 

The only thing I can think of is going back to the constructor conditions listed for [std::lock_guard()](http://en.cppreference.com/w/cpp/thread/lock_guard/lock_guard). Maybe some other thread owns the mutex returned from ```Emu.GetCoreMutex()``` when we are trying to create the ```std::lock_guard``` around it.

**Comment by sturmE** [comment] 2015-03-02 04:12
I figured it out. This runtime error was actually a side effect of the real problem.  The real problem was the failure to create a shared memory object when the vm starts up. Here's the fix I had to do.

```
diff --git a/rpcs3/Emu/Memory/vm.cpp b/rpcs3/Emu/Memory/vm.cpp
index 93b0482..be6884e 100644
--- a/rpcs3/Emu/Memory/vm.cpp
+++ b/rpcs3/Emu/Memory/vm.cpp
@@ -37,7 +37,7 @@ namespace vm

                return base_addr;
 #else
-               int memory_handle = shm_open("/rpcs3_vm", O_RDWR | O_CREAT | O_EXCL, 0);
+               int memory_handle = shm_open("rpcs3_vm", O_RDWR | O_CREAT | O_EXCL, 0);

                if (memory_handle == -1)
                {
```

**Comment by Syphurith** [comment] 2015-03-02 10:27
@sturmE about the `shm_open` in `sys/mmap.h`, from [opengroup](http://pubs.opengroup.org/onlinepubs/007908799/xsh/shm_open.html):

If name begins with the slash character, then processes calling shm_open() with the same value of name refer to the same shared memory object, as long as that name has not been removed. If name does not begin with the slash character, the effect is **implementation-dependent**.

**EDIT** Eh.. Have you ever tried with your build? Would you have similar gameplay as far as those on Linux and Windows? BTW you can try modify [its third param. `mode`](http://stackoverflow.com/questions/21368355/macos-x-c-shm-open-fails-with-errno-13-permission-denied-on-subsequent-runs).

**EDIT** Orz. I got [this](http://src.chromium.org/svn/trunk/src/base/memory/shared_memory_posix.cc) from chromium source.
```
Q: Why not use the shm_open() etc. APIs?
A: Because they're limited to 4mb on OS X.  FFFFFFFUUUUUUUUUUU
```
The function call may be replaced for OSX..

**Comment by Nekotekina** [comment] 2015-03-02 12:54
According to above link,
int memory_handle = shm_open("/rpcs3_vm", O_RDWR | O_CREAT | O_EXCL, S_IRUSR | S_IWUSR);

This may be worth trying. May require reboot to delete previous rpcs3_vm object if it once failed to create.

4 Mb limitation - maybe it's only applied to 32 bit? It's hard to believe.

**Comment by sturmE** [comment] 2015-03-02 14:36
Ya, I found some posts on stackoverflow detailing those same changes. 

```
int memory_handle = shm_open("/rpcs3_vm", O_RDWR | O_CREAT | O_EXCL, S_IRUSR | S_IWUSR);
```

That line did indeed make it work. Now I am running into some assertion failures, even though I'm quite sure they are turned off in my build, but that's another story.

BTW thanks for the information.

**Comment by robxu9** [comment] 2015-03-03 03:08
Yeah, shm_open definitely needs a mode, unless you want to run rpcs3 as root to ignore those permissions on subsequent runs or continuously reboot your computer. /sigh

**Comment by tambry** [comment] 2015-03-25 19:20
Does this problem persist?

**Comment by sturmE** [comment] 2015-03-26 01:59
@tambry Not for me.

**Comment by tambry** [comment] 2015-03-26 05:27
I'll close this. If anyone has more problems, I guess they can open another issue.

**Closed by tambry** 2015-03-26 05:27 UTC
